### ISSUE TITLE
Unable to build the current branch locally

### ISSUE THREAD

**Issue by laurentpetit** [vogellacompany/com.vogella.vde#101]
Hello,

I cloned the repository and tried to build it. I was unsuccessful.

The maven "stacktrace" is here: https://gist.github.com/laurentpetit/2004c6c0b937065cfec2

The specific commit at the time of filing this issue: 2b215df5d5d345971b4d4bce443d4d183d410cd1

Any help would be greatly appreciated

**Comment by vogella** [comment]
Thanks @laurentpetit I put this on my list, next week I will be very, very busy but I should have time in the week of 24. Nov. Unfortunately I cannot assign a reminder to a Github issue, in case I forget, please feel free to remind me.

**Comment by laurentpetit** [comment]
Nevermind. The error disappeared. Was probably a temporary network issue.
