### ISSUE TITLE
Voclipse Welcome Page 

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#11]
Voclipse should have it's own Welcome Page.

**Comment by vogella** [comment]
The welcome page is HTML?
Am 06.12.2013 10:23 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Yes/Nope, there are different ways to design the welcome page. 
1. Reusing the Universal Intro[1]
2. Write an own Intro, which can for example display html content.

We are currently using no.1 and just contribute to the given extension points. 
The Universal Intro is very extensible, so that every plugin can contribute to this and add project specific information to the welcome page. It has the full load of features with own theming, references to allkind of eclipse content (like wizards), shows news about new installed feature. But IMHO, from the user perspective no one uses these features. 

I would suggest:
If we want to have just want to provide links to vogella.com we stick with the solution we already have.
If we want a more "branded" welcome page, we should write an own intro and supply static html content or uses content from a special vogella.com website.

**Comment by hendrikstill** [comment]
In case you just skiped the welcome page ... as I do every time. Here is a screenshot of the current solution.
![welcome](https://f.cloud.github.com/assets/374528/1691240/6bd2a922-5e5d-11e3-9d31-284070b8214d.png)

**Comment by hendrikstill** [comment]
and here the linke to the helppage for the universial intro:
http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fua_intro_universal.htm&cp=2_0_19_0_2

**Comment by vogella** [comment]
Universal introduction is good enough. I think it would be helpful if we
could add a small text section to it about the voclipse build explaining
what it is. Is that feasible?

2013/12/6 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
The welcome is configured in the /com.vogella.vde/intro/vogella-webresources.xml . Guess I have to document this. 
The format definition can be found here [1]

[1]http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2FintroContentFileSpec.html

**Comment by hendrikstill** [comment]
@vogella could you add some real text, instead of the  Lorem ipsum ?

**Comment by vogella** [comment]
I committed the change, but the update of voclipse reports nothing has changed.
