### ISSUE TITLE
Integrate Findbugs in voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#13]
I suggest to add Findbugs to voclipse http://www.vogella.com/articles/Findbugs/article.html

**Comment by hendrikstill** [comment]
Same as Easyshell... licensed under lgpl.

**Comment by vogella** [comment]
I think lgpl is fine to integrate.

2013/12/9 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Findbugs seems use a old fashion update site istead of a p2-Updatesite:
http://findbugs.cs.umd.edu/eclipse-candidate/site.xml

Tycho isn't able to use this.
There is a workaround for this[1] which includes a lot of work. 
[1]http://tonnymadsen.blogspot.de/2013/05/tycho-and-pre-p2-update-sites.html

**Comment by vogella** [comment]
Is it difficult to setup a Tycho build for FindBugs? If not I can ask
Andrej if we accepts contributions for this. Note Andrej is a p2 hater...

2013/12/9 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Seems that they already have/try to use tycho[1] I didn't get the maven build to run. 

I guess(don't really know) that findbugs has some external dependencies, which would make it harder to get the tycho build run. But I'm sure it will take a complete day or more and I have still some other issues open, like the surefire stuff for the cbi platform build. 

[1]https://code.google.com/p/findbugs/source/browse/eclipsePlugin/pom.xml

**Comment by vogella** [comment]
OK, lets part this issue. Findbugs is just a detail and Andrej is not
postive about p2 and Eclipse 4.

2013/12/9 Hendrik S notifications@github.com

**Comment by vogella** [comment]
Not possible at the moment, because FindBugs uses old update site.
