### ISSUE TITLE
Integrate EasyShell into voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#14]
Not sure where the update site can be found, see here: http://marketplace.eclipse.org/content/easyshell

**Comment by vogella** [comment]
Update site: http://pluginbox.sourceforge.net/

**Comment by hendrikstill** [comment]
EasyShell is licensed under lgpl http://pluginbox.sourceforge.net/lgpl.html
Guess this is better than gpl, but I'm not sure what is required to include products like this. 
Should we still integrate it?

**Comment by vogella** [comment]
I think lgpl is fine to integrate.

2013/12/9 Hendrik S notifications@github.com
