### ISSUE TITLE
Update Voclipse Platform CBI updatesite.

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#17]
We should use the archive files instead of a reference to the jenkins workspace

**Comment by vogella** [comment]
+1, I can upload the generator code. Maybe you can fix it directly in the
generator?
Am 09.12.2013 17:35 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
I'm not sure whats your intention is.
This issue was meant as a "personal reminder" to not to forget the integration of the archived build files from the jenkins aggregator job, which is currently link to the  workspace.

So I just wanted to change the standart updatsite from
http://download.vogella.com/p2/C-MASTER-eclipse.platform.releng.aggregator/workspace/eclipse.platform.releng.tychoeclipsebuilder/sdk/ (...)

to 
http://download.vogella.com/p2/C-MASTER-eclipse.platform.releng.aggregator/lastStable/archive/eclipse.platform.releng.tychoeclipsebuilder/sdk/ (...)

**Comment by vogella** [comment]
Ah sorry, In though you wanted to update voclipse.com with the new and
correct URL. Please ignore my statement.
Am 09.12.2013 17:54 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Solved! @vogella  I opened a new Issue for the voclipse.com site  #18
