### ISSUE TITLE
Update voclipse.com

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#18]
Currently voclipse.com is referencing to the old buckminster based voclipse build. We should reference to the new builds.

**Comment by vogella** [comment]
Can you adjust the path in the /com.vogella.website.generator.navigation/templates/voclipse/index/index_middle.ftl file?

I updated the file and you only need to adjust:

<#assign var_voclipse_kepler = "https://build.vogella.com/ci/job/M-MASTER-voclipse/">
<#assign var_voclipse_luna = "https://build.vogella.com/ci/job/M-MASTER-voclipse/">

**Comment by hendrikstill** [comment]
Do I have access to the repo? I don't see anything that could match the path.

**Comment by vogella** [comment]
Sorry, added you to https://github.com/vogella/com.vogella.website
