### ISSUE TITLE
Manage Updates of default Settings

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#19]
I'm not sure if the settings of voclipse ,e.g.: line numbers, are also updated by the voclipse update mechanism.

I think both possible situations are bad:
-Overriding: Maybe the user did a specific change
-No update: The user will not have the newest settings up to date.

I think we could integrate workspace mechanics for this.

**Comment by hendrikstill** [comment]
With the latest update (change of default settings) I experienced that new changes will be set after an update.

**Comment by vogella** [comment]
I think if the user changes the setting it will be persisted in .metadata
and not overriden. New values should be set IMHO if the user did not change
them. So I think all is good and well.

2013/12/11 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Sounds good, I'll validate this!

**Comment by vogella** [comment]
Lets reopen if we see issue.
