### ISSUE TITLE
Add standart Updatesites

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#2]
Voclipse should come with pre configured updatesites

**Comment by hendrikstill** [comment]
The current build:
https://build.vogella.com/ci/job/HendrikStill-CBI-VDE/46/
has the voclipse repo as updatesite, which works pretty well. 

The downside: 
-To still provide different versions, Kepler and Luna, we have to configure different update sites.
voclipse Keplers updatesite would be: 
http://download.vogella.com/p2/HendrikStill-CBI-VDE/lastStable/archive/com.vogella.vde.product/target/repository/

voclipse Luna updatesite would be:
http://download.vogella.com/p2/HendrikStill-CBI-VDE-Luna/lastStable/archive/com.vogella.vde.product/target/repository/

This differences can not be handled by the current solution via maven profiles._we have a maven profile for the kepler build which is default and a profile for the luna build, to maintain only one branch but build two versions_

My suggestion would be to have two different products and include them depending on the chosen profile.
One for kepler: /com.vogella.vde.kepler.product
And one for luna: /com.vogella.vde.luna.product

**Comment by vogella** [comment]
+1
Am 06.12.2013 11:18 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
I spend a lot of time on solving this problem with maven resource filters, this would still allow a single product.
This seems not to work, due to some issues with tycho. 
I will go the way I described in the last message.

**Comment by hendrikstill** [comment]
Currently default updatesites are set depending on the release(luna or kepler).
This is possible using two different products and including theme depending on the chosen profile, as described previously. 

Please note that the results of the luna build are now archived in the <b>com.vogella.vde.luna.product</b> product

http://download.vogella.com/p2/HendrikStill-CBI-VDE-Luna/lastStable/archive/com.vogella.vde.luna.product/target/products/
