### ISSUE TITLE
Use Symlink to avoid redundancy

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#20]
040_voclipse.xml 

Similar to the pom.xml from the root directory this pom allows to build the whole voclipse IDE. It should say in-sync with the root pom.xml.

---

I just learned that Git support symlinks, see http://www.vogella.com/articles/Git/article.html#gitfaq_symlinks

I therefore suggest that you remove the redundancy and have only one pom.xml and use a symlinks for the other.

Also please update the documentation.

**Comment by hendrikstill** [comment]
The pom.xml can not be used with symlinks, because it uses relative paths to find the including maven modules.
Since the #fbd3fc8 the syncing of the root pom and aggregator pom is no more required.

**Comment by vogella** [comment]
Please update voclipse documentation
