### ISSUE TITLE
com.vogella.vde.luna.product necessary?

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#23]
A plug-in can store several product configuration files. Maybe we can move the com.vogella.vde.luna.product and its p2.inf file to the "com.vogella.vde.product"?  

If we do this, we should also rename com.vogella.vde.product to com.vogella.vde.kepler.product.

At least I was confused by the setup. I modified com.vogella.vde.product and was surprised that the new feature was not included in the luna build.

**Comment by hendrikstill** [comment]
The two different products are needed to configure different update sites.

Also we need one project per product file,due to limitations of tycho, which only allows to include one product file per build artifact.
