### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#25]
Add the new voclipse icons for the linux/mac/windows launcher

**Comment by hendrikstill** [comment]
Eclipse Product Editor shows warnings for the windows ICO File, so we should test it on a windows machine before we close this bug

**Comment by hendrikstill** [comment]
I tested voclipse on a windows machine, seems that the icons are currently not working

**Comment by hendrikstill** [comment]
Voclipse Application Icons are currently not included:
java.io.FileNotFoundException: /var/lib/jenkins/jobs/HendrikStill-CBI-VDE-Luna/workspace/com.vogella.vde.luna.product/target/products/com.vogella.vde.luna.product/com.vogella.vde/icons/launcher/xpm/256x256.XPM (No such file or directory)
...

Build Log: https://build.vogella.com/ci/job/HendrikStill-CBI-VDE-Luna/64/console

**Comment by vogella** [comment]
I renamed XPM to xpm. Maybe adjust the build.properties for this?

2014/1/2 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
e57d7cfcdc87d0bcfce819ee3bccfdee51b02679 fixed the references to the xpm files. I guess the ICO file has still some problems.
I'll try to convert the ico file like tom schindl describes it on his blog.
http://tomsondev.bestsolution.at/2007/06/26/branding-for-windows-how-to-create-ico-files-automatically/

**Comment by hendrikstill** [comment]
All warnings are fixed and windows icon is displayed correctly. We still have to validate the two other OSes

**Comment by vogella** [comment]
Cool!

2014/1/2 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Build also bundles correct xpm, guess we can close this issue
