### ISSUE TITLE
Check if Voclipse is updatable 

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#3]
Verify if voclipse is updatable via its own updatesite and also updateable with the standart eclipse repo (so that jdt will update without updating the vde.feature)

**Comment by hendrikstill** [comment]
Voclipse is currently updateable with some restrictions.
1. It is not possible to update voclipse if a new updatesite with dependencies from this is added to the feature, because the needed updatesite known to the current voclipse installation. 
2. Voclipse only updated depencies if the main feature changes. It is not possible to update the just the m2e plugin.

Solutions:
1. Supply a mirror p2 updatesite which includes every need plugin, so new added features will be available on the central vogella p2 updatesite
2.Add the features as root feature (which is currently not possible out of the box see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=361722)

**Comment by hendrikstill** [comment]
Also negative  is that we currently supply unsigned code which lets the security message popup for every updated feature. The signature verification is done by the jvm so we can not easily include a self signed certificate to the trusted certificates.

**Comment by vogella** [comment]
I vote for option 2.), maybe ask the Tycho guys in the bug report if this
can already be tested in a Tycho milestone build? Sometimes it is good to
remind committers of a bug report.
Am 09.12.2013 14:24 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Actuality I meant that restriction 1. could be solved by solution 1. and restriction 2. by solution 2. . So solution 2. will not fix the restrictions of the new added plugin. 

I don't find any changes in the tycho git repo which are depending on this bug. 
The given patch is just a comfortable method of calling the p2 director directly,which is also possible with a tycho-extras plugin[1]. 

[1]http://codeiseasy.wordpress.com/2013/07/02/adding-features-to-an-existing-product/

**Comment by vogella** [comment]
Which solution is easier? Use Tycho with the p2 fix or use the tycho-extra
plugin? I think having the option to update a feature independendly is a
MUST requirement.

2013/12/10 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
The tycho-extra solution has some significant drawbacks:
- The approach only generates a single platform build. You need to replicate all of the director and assembly calls for each platform you wish to build for. Tycho nicely loops over all the platforms you specify in your environment section.
- The assembly zip seems less efficient than the Tycho product zip. Installing only a simple feature resulting in a zip file ~60% larger than the original.
- The director application does not take advantage of the local bundle cache Tycho uses.

Especially the single platform point does not fit well in our concept.

I haven't tested the fix from Peter Muessig[1], but I guess this is the preferable solution. But the use of specific code would not support the portability of our solution. 

Maybe we can help to integrate this fix into tycho 0.20 . But I'm not sure if this fix will be accepted by the tycho team.

[1]https://bugs.eclipse.org/bugs/show_bug.cgi?id=361722#c4

**Comment by vogella** [comment]
> Maybe we can work help to integrate this fix into tycho 0.20 . But I'm
> not sure if this fix will be accepted by the tycho team.

The bug is marked for 0.20, so it looks like the Tycho team is will to look
into that. Maybe you can offer to help in the Bug report, e.g. for testing
or integrating the patch?

2013/12/13 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
I'm sure they want to fix the issue, but I'm not sure if they want to fix it with the given patch. 

I already offered help to some some other issues, but until now was not able to help until now due to the lack of time/knowledge. So before I do that, I would like to be sure that I'm really able to help there. 

First I would try to get the patch work locally.

**Comment by vogella** [comment]
> So before I do that, I would like to be sure that I'm really able to help
> there.

Sounds great. I guess one of the questions I would have, is how to use a
local (patched) version of Tycho, looks to me as if Tycho is downloaded by
Maven.

2013/12/13 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Yes for this patch, you first have to build tycho from source

Am Fr 13 Dez 2013 12:04:07 CET schrieb Lars Vogel:

> Which solution is easier? Use Tycho with the p2 fix or use the
> tycho-extra
> plugin? I think having the option to update a feature independendly is a
> MUST requirement.
> 
> 2013/12/10 Hendrik S notifications@github.com
> 
> > Actuality I meant that restriction 1. could be solved by solution 1.
> > and
> > restriction 2. by solution 2. . So solution 2. will not fix the
> > restrictions of the new added plugin.
> > 
> > I don't find any changes in the tycho git repo which are depending
> > on this
> > bug.
> > The given patch is just a comfortable method of calling the p2 director
> > directly,which is also possible with a tycho-extras plugin[1].
> > 
> > [1]
> > 
> > http://codeiseasy.wordpress.com/2013/07/02/adding-features-to-an-existing-product/
> > 
> > —
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/vogellacompany/com.vogella.vde/issues/3#issuecomment-30215270
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vogellacompany/com.vogella.vde/issues/3#issuecomment-30501748.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2.0.22 (GNU/Linux)
> Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBAgAGBQJSqvVfAAoJECjZOs4dIxis0wsH+wVkF7lLwxHxOoAQX7agJBSr
qWZ2Sq22q8PJx79+vkuZrRQZ+TDo7kqYs6ttWG4JAzd79TxjkLhdxdFjTyDDoYJG
64MLabBOwGWYBSxUSyN+OTne4m5l7ogswJoYaiRY8FUKbyoGrkS9qV+6ASz1FveY
lqSPHunG/qeqrNMbqu2eewqRz8y6CtMDrEcA6tDbvjx7q4+G4CkqmorGGPVxJAU/
3b9kpNJ2Ig1IP1lfIaTCxEjcySYJmKfxlhI2LVhofWqceFeOFXkpc5lcgHmbFQh1
0af+3+L/4VrhCMeE/TGJnm9VIyjv1+V13DVBBitcoMhY5j2XZu2al25a85TT82Q=
=brwv
-----END PGP SIGNATURE-----

**Comment by vogella** [comment]
http://wiki.eclipse.org/Developing_Tycho

2013/12/13 Hendrik S notifications@github.com
