### ISSUE TITLE
[CBI] Add API Baseline to the build process

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#31]

**Comment by hendrikstill** [comment]
Removed -P!api-generation 

Build 61 should integrate the api files
https://build.vogella.com/ci/job/C-MASTER-eclipse.platform.releng.aggregator/61/

**Comment by vogella** [comment]
This is a bit annoying, if I do platform development (eclipse.platform.ui) I get a lot of errors. I though this was only for PDE but if this is also for Eclipse UI, this has a high priority.

Errors occurred during the build.
Errors running builder 'API Analysis Builder' on project 'org.eclipse.e4.ui.css.swt.theme'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.e4.ui.workbench'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.e4.ui.workbench.swt'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.e4.ui.workbench.renderers.swt'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.e4.ui.workbench.addons.swt'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.workbench'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.browser'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.forms'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.navigator'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.views'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.ide'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.views.properties.tabbed'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.navigator.resources'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.ide.application'.
org/eclipse/pde/internal/core/PDEStateHelper
Errors running builder 'API Analysis Builder' on project 'org.eclipse.ui.workbench.compatibility'.
org/eclipse/pde/internal/core/PDEStateHelper

**Comment by hendrikstill** [comment]
I've currently no idea why this happens. Can you validate that this does not happen with the newest CBI Builds? 
http://download.vogella.com/p2/C-MASTER-eclipse.platform.releng.aggregator/lastStable/archive/eclipse.platform.releng.tychoeclipsebuilder/sdk/target/products/

**Comment by vogella** [comment]
CBI Build works with API baseline but voclipse not.

2014/1/1 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Defining a API Baseline by using the current CBI Build and selecting Voclipse as Location works, but I have currently no clue why this does not work. Bug #9 could be related to this. 
Maybe the mix of CBI/Milestone Plug-ins is responsible for this behavior. 

[Edit]
Corrected Bug No.

**Comment by vogella** [comment]
> Defining a API Baseline by using the current CBI Build and selecting
> Voclipse as Location works, but I have currently no clue why this does not
> work.

Verstehe ich nicht, widerspricht sich der Satz nicht? Kann man voclipse
verwenden um eine API Baseline im CBI Build zu setzen?

2014/1/2 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Ich meinte damit, dass man mit der CBI Eclipse Version, das voclipse Directory als Quelle für die API Baseline setzten kann. Damit kann ich quasi ausschließen, dass die Plug-ins, welche mit voclipse ausgeliefert werden schuld an der ganzen Sachen sind. Hätte ja sein können, dass Plug-ins eventuell API Beschreibungen fehlen. 

Der Fehler sollte also in der Anwendungsebene liegen.

**Comment by vogella** [comment]
Klingt so, wahrscheinlich irgendein Check in PDE. Haben wir das Source
Feature von PDE in voclipse?
Am 02.01.2014 14:27 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Jop, Source von der PDE liefer wir mit aus.

**Comment by hendrikstill** [comment]
Könnte tatsächlich an unterschiedlichen Quellen für die Plug-ins liegen. 
org.eclipse.pde version 3.8.200 CBI
org.eclipse.pde.ui version 3.8.100 Eclipse Milestone Build

**Comment by vogella** [comment]
Habs gerade mal probiert im Source mir anzuschauen, aber
org.eclipse.pde.api.tools.ui scheint keinen Source zu haben. Kannst Du das
entsprechende Source Feature hinzufügen?

Debug Einstiegspunkt wäre:  ApiBaselineWizardPage bzw. ApiBaselineWizard.
Wenn der Source da wäre könnte man das mit Strg+Shift+T öffnen...

2014/1/2 Hendrik S notifications@github.com

**Comment by vogella** [comment]
> Könnte tatsächlich an unterschiedlichen Quellen für die Plug-ins liegen.

Hm, ev. man nur die Quellen von Eclipse nutzen, um zu sehen, ob das dann
funktioniert?

2014/1/2 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
> Habs gerade mal probiert im Source mir anzuschauen, aber
> org.eclipse.pde.api.tools.ui scheint keinen Source zu haben. Kannst Du das
> entsprechende Source Feature hinzufügen?

bei mir ist org.eclipse.pde.api.tools.ui.source vorhanden, allerding nicht der passende source zu dem verwendetem runtime bundle. 

![image](https://f.cloud.github.com/assets/374528/1858541/4b722a2c-778f-11e3-811e-4be284b1eb04.png)

Ich werde mal die Java8 Featurepatches rausschmeißen und gucken ob es so klappt.

**Comment by hendrikstill** [comment]
So it seems that the problem is caused by the combination of CBI Build and Java 8 Feature Patches
![image](https://f.cloud.github.com/assets/374528/1858658/601a4da8-7792-11e3-820c-a2f160fbcb0d.png)

If you update your voclipse the Java 8 Feature Patches will be uninstalled and the api baseline will work properly

**Comment by vogella** [comment]
Can you please test the feature patch with a Vanilla Eclipse SDK download
and report a PDE bug if the behavior is the same?

2014/1/7 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
PDE for Java 8 has also the problem the the Vanilla Eclipse SDK.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=425117

**Comment by vogella** [comment]
JUHU!

2014/1/8 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Guess we can close this bug and reopen vogellacompany/com.vogella.vde#4
