### ISSUE TITLE
Use root level Feature

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#35]
try to add features as root level features with tycho addons

**Comment by hendrikstill** [comment]
follow up for #3

**Comment by hendrikstill** [comment]
Changes to allow this are discussed here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=361722

**Comment by hendrikstill** [comment]
Seems that a fix is on the way:
https://git.eclipse.org/r/#/c/21742/

**Comment by vogella** [comment]
Cool. If you had time, you could pull in the change and test it. ;-)

2014-02-13 21:24 GMT+01:00 Hendrik S notifications@github.com:

**Comment by vogella** [comment]
Fixed in voclipse with the latest commits.

![image](https://f.cloud.github.com/assets/139910/2320956/b49afb66-a398-11e3-9d8e-0eb977fe11db.png)
