### ISSUE TITLE
Why is the "Default theme" included into voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#38]
I still see the "Default theme" included into voclipse. This has been removed by me a while ago from the Eclipse source base. Can you please check where is comes from?

**Comment by hendrikstill** [comment]
Do you have a link to the bug repo?

**Comment by vogella** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=371785
Am 29.12.2013 15:21 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
I have to validate, if this also happens on the vanilla version.

The plug-in org.eclipse.platform, which should contain this changes is definitely from our last cbi build.
So, I've no idea why this still available.

**Comment by hendrikstill** [comment]
![image](https://f.cloud.github.com/assets/374528/1915650/ee5109c6-7d6a-11e3-9bce-9cfe3ebb48e7.png)

CBI Build has exactly the same behavior. Do I get something wrong?

**Comment by vogella** [comment]
I was actually pointing to the "Theme" but in a new download of voclipse the default entry is gone. Maybe it was cached. 

Closing this issue as solved.
