### ISSUE TITLE
Add Java 8 support for JDT

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#4]
It has to be added the feature patches from :

 http://dist.springsource.com/snapshot/TOOLS/java8/e43

**Comment by vogella** [comment]
Can you add some documentation to vogellabuilds about how you added the
feature patches?

2013/12/5 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Java 8 support was temporary removed, because it's currently only supported by 4.3

**Comment by vogella** [comment]
I think we can close this, as the JDT development handles this. No need from our side to do something.
