### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by Mailaender** [vogellacompany/com.vogella.vde#40]
I experimented with Linux packaging at https://github.com/Mailaender/com.voclipse.packaging starting with RPM because I can test those without a VM. However the same Maven plugin also claims to have DEB support so I will do that later. Looks like https://build.vogella.com/ci/job/C-MASTER-com.voclipse.packaging/ requires `rpmbuild` to be installed @vogella for the build to run on our CI server.

It is not pure Java, but some kind of Maven wrapper. I hope this can be integrated into the build at some time. You will notice that there is still a lot TODO, but I wanted to get started with something. The http://freedesktop.org/Standards/menu-spec desktop shortcut is done:

![voclipse-desktop](https://f.cloud.github.com/assets/756669/1847508/e3ef2f4c-7650-11e3-9f25-4dacedc7f96a.png)

However something is probably not quite right yet. I get one broken dependency because openSUSE does not have osgi(ant) which I just ignored. The IDE looks too empty. I think the plugins do not load properly.

![empty-voclipse](https://f.cloud.github.com/assets/756669/1847509/0b1e7eec-7651-11e3-9a8f-419059a74db8.png)

No idea why. Found this log http://paste.opensuse.org/view/simple/13d6b975 in my ~/.eclipse directory. It will also fail when I `cd /opt/voclipse && exec voclipse` so it is probably not a working directory problem.

**Comment by vogella** [comment]
sudo apt-get install rpm - done on the Jenkins build server.

2014/1/5 Matthias Mailänder notifications@github.com

**Comment by Mailaender** [comment]
Thanks. However it seems my SUSE rpmbuild behaves differently to Ubuntus here.

`Unable to create package. Command 'rpmbuild' returned a non-null exit code: 1`

Sadly it does not hand over the rpmbuild error message for debugging.

**Comment by hendrikstill** [comment]
I'm sorry for the confusion. 
@Mailaender as you already noticed, the C-MASTER-com.voclipse is the job for the old voclipse build from Markus Kuppe.
To avoid problems like this I renamed the depending jobs and deactived them on the jenkins build server. 

The jobs to build the new Voclipse (aka VDE) are 
HendrikStill-CBI-VDE : Kepler stable release
HendrikStill-CBI-VDE-Luna : Luna development release which also includes changes from the current development branches

The  build is documented on this site:
http://www.vogella.com/tutorials/voclipse/article.html

**Comment by vogella** [comment]
We should also rename the Hendrik jobs,
https://github.com/vogellacompany/com.vogella.vde/issues/41

2014/1/7 Hendrik S notifications@github.com

**Comment by Mailaender** [comment]
Success! https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ws/ now spits out an RPM.

**Comment by hendrikstill** [comment]
Great news. 
Lets build a package for arch so I can use Pacman :-P

**Comment by vogella** [comment]
Congratulations! A long running task, but finally success!

**Comment by Mailaender** [comment]
> Lets build a package for arch so I can use Pacman :-P

Next is probably DEB for @vogella and because that might be easier from Ubuntu plus I have scripts from @OpenRA and OpenChrom I can use as a template. However the task may not be that far fetched as we build https://github.com/OpenRA/OpenRA/tree/bleed/packaging/linux/pkgbuild from an Ubuntu build server, too. I just need to investigate where we got `pacman` and/or `makepkg` from.

**Comment by hendrikstill** [comment]
I was just joking :-) 
I also guess that the DEB distributions are more important.

**Comment by Mailaender** [comment]
Actually creating Arch Linux packages is somehow appealing as it is such a simple format. Putting it on my TODO.
