### ISSUE TITLE
Rename Jenkins jobs for voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#41]
Please rename 
HendrikStill-CBI-VDE    and HendrikStill-CBI-VDE-Luna to something more reasonable.

**Comment by hendrikstill** [comment]
This should be done carefully!
The current voclipse build has references to the updatesite which are based on the name of the jobs. 
Maybe we create a mirror or an alias url for the build results and repositories, to avoid problems like this, in the future.

**Comment by vogella** [comment]
I think now is a good time to rename the jobs. Nobody except you and me
(and maybe Matthias) is using voclipse and we should be OK with a new
download.

I think for future renames I could create a redirect on the HTTP server
pointing to the new update site. Not sure if that works with p2 but I think
it should.

2014/1/7 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Jobs are renamed to:
C-MASTER-com.vogella.vde
Updatesite: http://download.vogella.com/p2/C-MASTER-com.vogella.vde/lastStable/archive/com.vogella.vde.product/target/repository/

C-MASTER-com.vogella.vde.luna
Updatesite: http://download.vogella.com/p2/C-MASTER-com.vogella.vde.luna/lastStable/archive/com.vogella.vde.luna.product/target/repository/

**Comment by vogella** [comment]
Please also update 040_voclipse.xml in the voclipse tutorial

2014/1/7 Hendrik S notifications@github.com
