### ISSUE TITLE
Add PreferenceSpy to voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#42]

**Comment by hendrikstill** [comment]
We currently use the "Workspace URL" from the Jenkins build. 
http://download.vogella.com/p2/C-MASTER-PreferencesSpy/workspace/com.vogella.vde.preferencesspy.repository/target/repository/

I'm currently not able to configure this job to archive the build results, to have a "stable" link to the build results. 

First close this issue if we can use the archived build results

**Comment by hendrikstill** [comment]
Done
