### ISSUE TITLE
C-MASTER-eclipse.platform.releng.aggregator Jenkins job is broken

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#44]
Since last year (31.12.2013) the CBI aggregator job is broken.

<pre>
FATAL: No remotes found!
hudson.plugins.git.GitException: No remotes found!
</pre>

**Comment by hendrikstill** [comment]
Guess this could be the problem:
https://issues.jenkins-ci.org/browse/JENKINS-21057

I will try to build a small workaround

**Comment by hendrikstill** [comment]
Changed to manual/unmanged git commands and the remote repo instead of our local copy.

<pre>
#workaround for vogellacompany/com.vogella.vde#44
git clone -b master --recursive git://git.eclipse.org/gitroot/platform/eclipse.platform.releng.aggregator.git 
git checkout master
git pull --recurse-submodules
git submodule update
#end workaround 
</pre>

**Comment by hendrikstill** [comment]
I guess the best solution would be to downgrade the git and git client plugin to 1.4.6 [1]

[1]https://issues.jenkins-ci.org/browse/JENKINS-21057?focusedCommentId=191663&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-191663

**Comment by hendrikstill** [comment]
@vogella would this be possible?

**Comment by vogella** [comment]
Where is a Git and Git client update available, I try to install them.

2014/1/13 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
I guess the problem is the newest version 1.5. So instead of upgrading this we have to downgrade to 1.4.6. 
See the Jenkins Issue I've posted.

**Comment by vogella** [comment]
Ok I downgrade.

2014/1/13 Hendrik S notifications@github.com

**Comment by vogella** [comment]
Downgraded. I now get an syntax error with a very small test. I suggest to
upgrade again. https://build.vogella.com/ci/job/Test/1/console

2014/1/13 Lars Vogel lars.vogel@gmail.com

**Comment by hendrikstill** [comment]
:-P

**Comment by vogella** [comment]
Is it OK if I upgrade, or do you want to try to make this work with the
downgraded version?

2014/1/13 Hendrik S notifications@github.com

**Comment by vogella** [comment]
@hendrikstill, I wait for your answer. AFAICT currently Jenkins is broken.

2014/1/13 Lars Vogel lars.vogel@gmail.com

**Comment by vogella** [comment]
Sorry, can't leave Jenkins broken. Upgrading again to the latest plug-in

2014/1/13 Lars Vogel lars.vogel@gmail.com

**Comment by vogella** [comment]
https://build.vogella.com/ci/job/Private-M-MASTER-www.vogella.com/ seems to
run (and it is using sub-modules)

2014/1/13 Lars Vogel lars.vogel@gmail.com

**Comment by hendrikstill** [comment]
Sorry für die späte Rückmeldung, war gerade bei meinem Prof. 
Ich werde versuchen den Build über manuelle Git Befehle zum laufen zu bekommen.

**Comment by vogella** [comment]
Kein Problem wegen der Rueckmeldung.

Komisch, das submodules bei
https://build.vogella.com/ci/job/Private-M-MASTER-www.vogella.com/
funktionieren,
beim Aggregator run aber nicht.

Am 13. Januar 2014 15:07 schrieb Hendrik S notifications@github.com:

**Comment by hendrikstill** [comment]
C-MASTER-eclipse.platform.releng.aggregator is temporary fixed.
I guess the problem is caused by the combination of our local aggregator cloner job .

Lets wait for a fix from the jenkins guys

**Comment by hendrikstill** [comment]
<pre>
Updated
The main reason is that the remote configuration is not added to .git/config, after adding this manually the submodule update and build process works.
I'm using the Git Client 1.61 Plugin with Git 1.8.3.4 of my Mac OS X.
</pre>

Source: https://issues.jenkins-ci.org/browse/JENKINS-21057?focusedCommentId=191819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-191819

**Comment by vogella** [comment]
I think you removed the build trigger with the removal of the repository. Can you schedule the job to run daily?

**Comment by hendrikstill** [comment]
> I think you removed the build trigger with the removal of the repository. Can you schedule the job to run daily?

Done! The build now starts at 00:00 local time.
