### ISSUE TITLE
Provide ini file for Eclipse with better memory settings

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#47]
Would it be possible to provide settings for voclipse with improved memory settings?

See: 
http://www.vogella.com/tutorials/Eclipse/article.html#eclipse_memorysettings

**Comment by hendrikstill** [comment]
Yep via the Product. Under the tab "launching", is a parameter "VM Argumentens"

http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Feditors%2Fproduct_editor%2Flaunching.htm

**Comment by vogella** [comment]
OK, tried to add it with f150e3364ebcf98ce39f8e30c6c5a5fd30340a29. Please validate.

**Comment by hendrikstill** [comment]
Works! Just update the Voclipse installation.
