### ISSUE TITLE
Kepler build fails

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#48]
https://build.vogella.com/ci/job/C-MASTER-com.vogella.vde/114/console

<pre>
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.vogella.vde.product 0.1.0.qualifier
[ERROR]   Missing requirement: com.vogella.vde.product 0.1.0.qualifier requires 'org.eclipse.epp.mpc.feature.group [1.2.1.I20131002-1306]' but it could not be found
[ERROR] 
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from com.vogella.vde.product 0.1.0.qualifier to org.eclipse.epp.mpc.feature.group [1.2.1.I20131002-1306].; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.0.v_OTDT_r220_201306071800 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.1.v_OTDT_r221_201309101918 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; No solution found because the problem is unsatisfiable.] -> [Help 1]
</pre>

**Comment by vogella** [comment]
Ups, sorry. Thanks for fixing.
Am 20.01.2014 20:02 schrieb "Hendrik S" notifications@github.com:
