### ISSUE TITLE
preferencesspy p2 repository is not reachable

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#49]
<pre>
[WARNING] Failed to access p2 repository http://download.vogella.com/p2/C-MASTER-PreferencesSpy/lastSuccessful/archive/com.vogella.vde.preferencesspy.repository/target/repository, use local cache. Neither http://download.vogella.com/p2/C-MASTER-PreferencesSpy/lastSuccessful/archive/com.vogella.vde.preferencesspy.repository/target/repository/content.jar nor http://download.vogella.com/p2/C-MASTER-PreferencesSpy/lastSuccessful/archive/com.vogella.vde.preferencesspy.repository/target/repository/content.xml found.

</pre>

**Comment by vogella** [comment]
I don't see an archive step in https://build.vogella.com/ci/job/C-MASTER-PreferencesSpy/configure

**Comment by vogella** [comment]
Also no archive directory on http://download.vogella.com/p2/C-MASTER-PreferencesSpy/lastSuccessful/

**Comment by hendrikstill** [comment]
Is working again.

<pre>
[INFO] Fetching content.jar from https://raw.github.com/jeeeyul/eclipse-themes/master/net.jeeeyul.eclipse.themes.updatesite/ (4kB of 7.37kB at 0B/s)
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/I20140114130914/repository
[INFO] Adding repository http://download.vogella.com/p2/C-MASTER-PreferencesSpy/lastSuccessful/archive/com.vogella.vde.preferencesspy.repository/target/repository
[INFO] Adding repository http://download.jboss.org/jbosstools/updates/stable/kepler
</pre>

**Comment by vogella** [comment]
Did you change the Jenkins build job?

**Comment by hendrikstill** [comment]
yes, maybe we never noticed this warning :-( we should check the build log more often
