### ISSUE TITLE
Add e4 tools

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#5]
see title

**Comment by hendrikstill** [comment]
The current build works with:

org.eclipse.e4.core.tools.feature
org.eclipse.e4.tools.css.editor.feature
org.eclipse.e4.tools.css.spy.feature
org.eclipse.e4.tools.event.spy.feature
org.eclipse.e4.tools.orion.css.editor.feature

Only the org.eclipse.e4.tools.e3x.bridge.feature does not work, see log[1] 

@vogella do we need this feature, or do you have an idea to solve this?

[1]https://gist.github.com/hendrikstill/7803562

**Comment by vogella** [comment]
No, please leave Bridget out. I never install it, as it always creates
issues.

2013/12/5 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Okay, then this bug is closed
