### ISSUE TITLE
Context Menu in the Java Package Explorer does not work

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#50]
The rightclick menu in the does not work for me.
This just happens in the Java Package Explorer.

Maybe some changes from the CBI build in does not work.

**Comment by vogella** [comment]
Works for me.

2014/1/20 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
For me also, after exchanging the voclipse files manually instead of, updating voclipse with p2.
