### ISSUE TITLE
Add regex evaluation tools to voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#51]
There are several, need to find one and test

**Comment by vogella** [comment]
@hendrikstill is the following a p2 update site? http://regex-util.sourceforge.net/update/

**Comment by hendrikstill** [comment]
Nope, dont think so. It only provides a site.xml [1], but requesting artifacts.jar will give you a 404.
[1]http://regex-util.sourceforge.net/update/site.xml
[2]http://regex-util.sourceforge.net/update/artifacts.jar

**Comment by vogella** [comment]
OK lets close this for now close#51
Am 23.01.2014 00:29 schrieb "Hendrik S" notifications@github.com:
