### ISSUE TITLE
Putting an update site on Github or bintray

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#52]
I think it would be interesting to start placing our update site on Github, to avoid an overload of build.vogella.com in case voclipse gets successfull in the future.

@hendrikstill What do you think? I think for relatively "stable" things like the PreferenceSpy that would be really useful.

See http://www.vainolo.com/2013/03/06/creating-and-using-an-eclipse-update-site-using-maven-tycho-and-github/

**Comment by hendrikstill** [comment]
I'm pro serving the update site from another system then our build server. So changes at the buildsystem, like renaming jobs, do not affect the distribution of the build artifacts.

I'm not sure if we should distribute theme via github repos. IMHO the repo should only include the source code and a minimum of binaries. Adding the binaries to the "sourcecode repo" would end up in git logs like 
1. Adds Feature XYC
2. Jenkins: Updated binaries to version 1.
3. Fixes Bug ABC
4. Jenkins: Updated binaries to version 3.
...
This would make it also very hard to work on this repository.
After every push you have to fetch the new binaries.

Maybe we publish the build results on a sperated webserver or via the Amazon S3 service.

**Comment by hendrikstill** [comment]
Or whats about https://bintray.com/ 

It has also an plugin for maven: http://veithen.blogspot.de/2013/05/github-bintray-maven-release-plugin.html

**Comment by vogella** [comment]
Maybe we can create a separate Github repo for published artifacts?
Am 21.01.2014 16:03 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Sure, but I still like the bintray service, also other eclipse distributions like nodeclipse[1] use this as deployment site.

[1]https://bintray.com/nodeclipse/nodeclipse/nodeclipse-1

**Comment by vogella** [comment]
Is bintray free to use? If yes I'm +1 for it.
Am 21.01.2014 16:40 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Okay, it's only possible to upload 500mb in total. 
That would be okay for PreferenceSpy but not enough for voclipse. 

How would you implement the upload to github?

**Comment by vogella** [comment]
We could test this with Preferences to gain experience.
Am 21.01.2014 19:28 schrieb "Hendrik S" notifications@github.com:

**Comment by vogella** [comment]
I created an "vogella" account on bintray.com, so we could start testing.
But I don't see info how to copy files into the repo with Maven.
http://veithen.blogspot.de/2013/05/github-bintray-maven-release-plugin.html

2014/1/21 Lars Vogel lars.vogel@gmail.com

**Comment by vogella** [comment]
Maybe this can help:
http://blog.harawata.net/2013/07/hosting-eclipse-plugin-update-site-p2.html

2014/1/21 Lars Vogel lars.vogel@gmail.com

**Comment by vogella** [comment]
Sounds like nodeclipse.js is also using Github update sites now (See news)
http://www.nodeclipse.org
Am 21.01.2014 22:46 schrieb "Lars Vogel" lars.vogel@gmail.com:

**Comment by hendrikstill** [comment]
They push a composite repository to github, but not the binaries.[1] The binaries are still uploaded to bintray.
But this is also a great idea.  We could use this, and avoid the ugly problem with the p2.inf to add updatesite to the voclipse installations. 

Now back to bintray:
An upload of just the maven artifacts does not work, because our main goal is to publish the p2 repository. So this does not really work for us. 
The REST service allows only to upload single files. So we have to write some "upload/realse" script.
It seems that most of the projects on bintray upload there binaries manually via the web UI. 
Also the guy form [2] only uses the the REST as workaround to upload just artifacts.jar and content.jar.
It seems that bintray is not 100% p2-updatesite friendly.

Easiest way would be an FTP/Web server. I'm not sure how much traffic we get, but I would guess the small plug-ins 
do not generate to much traffic. 
In combination with the composite repository we could easily change the update site addresses, without any confusion on the user side, and allow later changes.  
You find more information about the composite repository at http://blog.vogella.com/2010/04/06/eclipse-p2-composite-repository/ ;-)

[1]https://github.com/Enide/eclipse-p2-composite-repository
[2]http://blog.harawata.net/2013/07/hosting-eclipse-plugin-update-site-p2.html

**Comment by hendrikstill** [comment]
Or we push the binaries to a separated repository on github ;-) as you said before.

**Comment by Mailaender** [comment]
That is somehow ugly as git is not the perfect solution for managing binaries. If you want to use the GitHub CDN, I suggest you use https://github.com/blog/1547-release-your-software

**Comment by vogella** [comment]
Releases can only be one zip file? That would work for the build result of
voclipse but not for the update site. Still I like the idea of releasing
voclipse via this Git release thing.

@Hendrik what do you think?

2014-02-03 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
I think you should use the http://developer.github.com/v3/repos/releases/ API and not the GUI drag and drop also to automatize the task.

**Comment by Mailaender** [comment]
See also https://github.com/blog/1645-releases-api-preview and https://github.com/textmate/textmate/blob/master/bin/upload for examples.

**Comment by hendrikstill** [comment]
Github releases have the problem that they just serve one singel file. If we want do distribute our 5 zip packages we have to create 5 releases, with non static urls. 

I don't find any services which can host our repository free, is easy enough to use and "professional".

Gitrepos have a disk quota of 1 GB, so we are not able to track old versions of the binary, but it is easy to use.
So why shouldn't we stay pragmatic and use a separated github repo to serve the p2 repos?

For the large zipfiles we could try the github release function or still use our download.vogella.com server.
I found a free and very easy to use cdn service called CoBlitz[1], which is fast as hell (tested with 2,7MB/s) and also serves some fedora files.
We just have to add the coblitz url to the download link.

<pre>
http://coblitz.codeen.org/download.vogella.com/p2/C-MASTER-eclipse.platform.releng.aggregator/lastStable/archive/eclipse.platform.releng.tychoeclipsebuilder/sdk/target/products/org.eclipse.sdk.ide-linux.gtk.x86_64.tar.gz
</pre> 

[1]http://codeen.cs.princeton.edu/coblitz/

**Comment by hendrikstill** [comment]
okay forget the coblitz service:

<pre>The CoBlitz system that runs on PlanetLab is now gradually closing down,</pre>

**Comment by Mailaender** [comment]
Maybe use @SourceForge. They are pretty big still with a large mirror network. See http://eclipse-cs.sourceforge.net/update/ for example.

**Comment by vogella** [comment]
I dislike SourceForge with their heavy advertisement and malware links. -1
for SourceForge

2014-02-04 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
You can hotlink them https://fedoraproject.org/wiki/Packaging:SourceURL

**Comment by Mailaender** [comment]
Maybe use GitHub releases for the installers https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ and Bintray for the update site?

**Comment by Mailaender** [comment]
See also http://blog.bintray.com/2014/03/11/hosting-your-eclipse-update-site-p2-on-bintray-com/

**Comment by Mailaender** [comment]
This may not even be required. I could download with 4 MB/s from https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ using the http://attraktor.org supplied internet line. The http://www.hetzner.de/hosting/unternehmen/rechenzentrum is probably giving us enough bandwidth.

**Comment by vogella** [comment]
I believe that download rate would decrease if > 20 people would download
voclipse.

2014-03-29 11:31 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by vogella** [comment]
We are now using Bintray for deployment, using the REST API to upload the p2 update site. I mark this one as closed.
