### ISSUE TITLE
Release voclipse as Open Source?

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#53]
Curently the Git repo for voclipse is still a private repo. @hendrikstill any specific reasons for that? I would like to release the repo.

**Comment by vogella** [comment]
Or in different words, I think it is OK to release it. Maybe others like to contribute.

**Comment by hendrikstill** [comment]
Sure why not, I think I have to make the my voclipse repo public for this.

**Comment by hendrikstill** [comment]
my repo is public, I guess you can change it too!

**Comment by vogella** [comment]
Great. thanks. I changed the vogellacompany one also to be a public repo. I plan to start blogging about voclipse next week, it is good to have the repo public. Maybe others will contribute.

**Comment by vogella** [comment]
Ah, by the way: Our issues are not also public.

**Comment by hendrikstill** [comment]
I guess we can close this issue.
