### ISSUE TITLE
Add ~ files to .gitignore

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#55]
Can you please add ~ file to the .gitignore file?

**Comment by Mailaender** [comment]
Sounds like something you should add to your system `.gitignore` file.

**Comment by vogella** [comment]
I think its good practice to have correct project .gitignore files instead
of relying on every developer to setup his global .gitignore
Am 25.01.2014 16:16 schrieb "Matthias Mailänder" notifications@github.com:

**Comment by hendrikstill** [comment]
.gitignore:

<pre>
# Ignore temporary backup files 
*~
</pre>
