### ISSUE TITLE
Cannot update voclipse with error message from Orbit

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#56]
I have no idea how long Orbit updates sites are available but the update mechanism fails.

![image](https://f.cloud.github.com/assets/139910/1985587/876a2e0e-8440-11e3-940e-19817e03f043.png)

Can you have a look?

**Comment by hendrikstill** [comment]
Okay, that is not good, I'll have a look at this

**Comment by hendrikstill** [comment]
feb2ff1 is just a temporary fix to get the build up again. 
I haven't found a "static" link to the newest repository.

**Comment by vogella** [comment]
Hab gerade bei Twitter gefragt:

_Chris Aniszczyk_ @cra
https://twitter.com/cra3mhttps://twitter.com/cra/status/426765506427629568

@vogella https://twitter.com/vogella the Recommendend builds should be
there forever http://download.eclipse.org/tools/orbit/downloads/
…http://t.co/d4Zt1TbsMC

http://download.eclipse.org/tools/orbit/downloads/

Kannst Du das umstellen?

2014/1/24 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Der Link ist aber kein P2 Repository

**Comment by vogella** [comment]
Unter dem Link findest Du die "Recommended" repos

2014/1/24 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
Okay, I used an recommended repository for fix feb2ff1

**Comment by vogella** [comment]
All good in this case. Thanks.
Am 24.01.2014 18:39 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Seems, that the currently used url is "stable"
