### ISSUE TITLE
Add Eclipse platform test plug-ins to voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#58]
I find it annoying that I have to add all the time the Eclipse test plug-ins to my workspace.

Why don't we add these plug-ins to voclipse so that they are available directly?

org.eclipse.core.tests.harness from the eclipse.platform.runtime repository
org.eclipse.core.tests.runtime from the eclipse.platform.runtime repository
org.eclipse.test.performance from the eclipse.platform.releng repository
org.eclipse.ui.tests from the eclipse.platform.ui repository
org.eclipse.ui.tests.harness from the eclipse.platform.ui repository

**Comment by vogella** [comment]
Hendrik, any reason not to do this?

**Comment by hendrikstill** [comment]
Except the size of the distributed files, I have no problem with this.

**Comment by vogella** [comment]
Can you set this up? Would be great, I'm current delivering an android
trsining
Am 28.01.2014 09:10 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Okay, this is maybe not a so good idea.
I've added the plug-ins to the luna build, which can use a repository of the cbi platform build.
The bundles are ... of-course ... loaded in the host eclipse instance and result in strange behaviorist like several testing perspectives. 
![image](https://f.cloud.github.com/assets/374528/2022358/8f882a18-884c-11e3-8bb4-37eda3143624.png)

The testing plug-ins should only be loaded at client-instances, when a eclipse application is started via the run-as command. 
 @vogella do you have any idea how to handle this?

**Comment by hendrikstill** [comment]
The commit a480b5f belongs to the branch eclipse_testing and is not in the master branch

**Comment by hendrikstill** [comment]
I guess we don't have any other alternative to solve this issue.
