### ISSUE TITLE
Create composite update site to update voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#63]

**Comment by hendrikstill** [comment]
Now we are using one central composit update site, which contains the reference to all needed p2 repositories.

**Comment by hendrikstill** [comment]
Add the following updatesite to your installation:
Voclipse Composit Updatesite - https://raw2.github.com/vogellacompany/com.vogella.vde/master/com.vogella.vde.luna.updatesite
