### ISSUE TITLE
Black splash look horrible if progress bar starts

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#65]
The voclipse black splash screen gets red during startup.

**Comment by vogella** [comment]
![image](https://f.cloud.github.com/assets/139910/2064560/b291e788-8ccf-11e3-80a7-4cb12c616e48.png)

**Comment by hendrikstill** [comment]
Looks like the same problem I had, when I tried to save the splashscreen as png.
It inverts the colors, but I don't know why. 
I'm not sure if own splashscreen implementation will fix this.

**Comment by Mailaender** [comment]
Could be a palette error.
