### ISSUE TITLE
Invisible error pop-up when launching from RPM

### ISSUE THREAD

**Issue by Mailaender** [vogellacompany/com.vogella.vde#66]
When testing my newly created RPM from https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ws/ I see the red splash for just a second #65 which disappears quickly and then I get an empty error popup:

![voclipse-invisible-error](https://f.cloud.github.com/assets/756669/2065229/78d3bfe0-8cdd-11e3-8938-7fffb6de6f57.png)

Nothing in the console. Not sure where to look for error logs as I also have a regular Eclipse 4.3.1 installed into `/usr/lib/eclipse`.

```
matthias@mPad-X230:~/.eclipse> ls
1364444378_linux_gtk_x86  openchrom-workspace  org.eclipse.platform_4.3.0_155965261_linux_gtk_x86  vogella-workspace
1421818527_linux_gtk_x86  openra-workspace     runtime-EclipseApplication                          workspace
```

Starting from `matthias@mPad-X230:/opt/voclipse> ./voclipse` results in the same behavior. It could be my fault, but I am not sure where to start debugging.

**Comment by hendrikstill** [comment]
Other Eclipse installations should not interfere with the voclipse installation. 
Are you able to select a workspace?

**Comment by Mailaender** [comment]
> Are you able to select a workspace?

Yes, `/home/matthias/.voclipse/default-workspace/` has been created, but is entirely empty.

**Comment by Mailaender** [comment]
Wait, there is a `.metadata` folder with `version.ini`:

``` ini
org.eclipse.core.runtime=1
```

**Comment by hendrikstill** [comment]
Can you try to run a manual "installed" version of voclipse kepler.
http://download.vogella.com/p2/C-MASTER-com.vogella.vde/lastStable/archive/com.vogella.vde.product/target/products/

Just unzip and try to run it.

**Comment by Mailaender** [comment]
That works:

![voclipse-unpacked](https://f.cloud.github.com/assets/756669/2065384/85369b38-8ce0-11e3-96bf-786a55c5d403.png)

which probably concludes it is a packaging error. However I don't know why. My `.spec` file actually does the same. Just unzip, move to `/opt/voclipse` and then some softlinks to `/usr/bin`. It installs icons/.desktop files for convenience. The http://software.opensuse.org/package/eclipse do the same with the vanilla Eclipse ZIPs where it seems to work without trouble.

**Comment by Mailaender** [comment]
Even `xdg-su -c voclipse` fails so it is probably not a permission problem.

**Comment by hendrikstill** [comment]
Maybe <code>-Declipse.consoleLog=true</code> helps

Source: http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html

**Comment by Mailaender** [comment]
Neither `./voclipse -Declipse.consoleLog=true` nor `voclipse -Declipse.consoleLog=true` dump anything into the terminal. :(

**Comment by hendrikstill** [comment]
okay, lets try <code>-debug</code>

**Comment by Mailaender** [comment]
```
matthias@mPad-X230:~> voclipse -debug
Start VM: -Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:PermSize=256M
-XX:MaxPermSize=512M
-Djava.class.path=/opt/voclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
-os linux
-ws gtk
-arch x86
-showsplash
-launcher /opt/voclipse/voclipse
-name Voclipse
--launcher.library /opt/voclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_1.1.200.v20130807-1835/eclipse_1506.so
-startup /opt/voclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
--launcher.overrideVmargs
-showLocation
-debug
-vm /usr/lib/jvm/java-1.7.0-openjdk-1.7.0/jre/bin/../lib/i386/client/libjvm.so
-vmargs
-Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:PermSize=256M
-XX:MaxPermSize=512M
-Djava.class.path=/opt/voclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar 
Install location:
    file:/opt/voclipse/
Configuration file:
    file:/opt/voclipse/configuration/config.ini loaded
Configuration location:
    file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/
Configuration file:
    file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/config.ini loaded
Loading timestamp file from:
         file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/   .baseConfigIniTimestamp
Timestamps found: 
         config.ini in the base: 1391438798000
         remembered 1391438798000
Shared configuration location:
    file:/opt/voclipse/configuration/
Framework located:
    file:/opt/voclipse/plugins/org.eclipse.osgi_3.9.1.v20130814-1242.jar
Framework classpath:
    file:/opt/voclipse/plugins/org.eclipse.osgi_3.9.1.v20130814-1242.jar
Splash location:
    /home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/org.eclipse.equinox.launcher/com.vogella.vde_0.1.0.201402021231/splash.bmp
Debug options:
    file:/home/matthias/.options not found
Time to load bundles: 3
Starting application: 1838

```

**Comment by hendrikstill** [comment]
Following lines look suspicious, but I'm sure that this does not have to do something with the startup problem.

<pre>
Configuration location:
    file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/
Configuration file:
    file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/config.ini loaded
</pre>

<code>-arch x86</code> ??? Are you still using a 32-Bit JavaVM?

**Comment by Mailaender** [comment]
`.eclipse/1364444378_linux_gtk_x86/configuration/config.ini:`

``` ini
#This configuration file was written by: org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser
#Mon Feb 03 15:50:42 CET 2014
osgi.sharedConfiguration.area=file\:configuration/
```

> Are you still using a 32-Bit JavaVM?

That should be correct. I am using a Intel Core i5 vPro CPU in my sub-notebook.

```
matthias@mPad-X230:~/Downloads> java -version
java version "1.7.0_51"
OpenJDK Runtime Environment (IcedTea 2.4.4) (suse-24.13.5-i386)
OpenJDK Server VM (build 24.45-b08, mixed mode)
```

**Comment by hendrikstill** [comment]
Hmmm ... a diff between the unpacked zip folder and the /opt/voclipse/ folder?

**Comment by Mailaender** [comment]
https://gist.github.com/Mailaender/8785816

**Comment by hendrikstill** [comment]
woops this are a lot of different files or not? 
For example the executable:
https://gist.github.com/Mailaender/8785816#file-opt-zip-diff-L2862

**Comment by Mailaender** [comment]
Yeah, those builds might have a time gap of ~1 weekend. I will try to do a cleaner one with something that compares better.

**Comment by Mailaender** [comment]
I updated my package to Luna which fixes it so I am all for #67. I also save the last successful build at https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ for the public:

![voclipse-luna](https://f.cloud.github.com/assets/756669/2098664/4afcd746-8f30-11e3-9912-64f1a7f596a2.png)

**Comment by vogella** [comment]
Yes, Luna is at the moment under heavy development and Kepler feels already
outdated to me. I will remove it from the voclipse.com website.

2014-02-06 14:12 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
I can't start it again. It seems to loop indefinitely (splash appears all over again):

```
Time to load bundles: 2148
Start VM: -Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:PermSize=256M
-XX:MaxPermSize=512M
-Djava.class.path=/opt/voclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
-os linux
-ws gtk
-arch x86
-showsplash
-launcher /opt/voclipse/voclipse
-name Voclipse
--launcher.library /opt/voclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_1.1.200.v20131025-1931/eclipse_1601.so
-startup /opt/voclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
--launcher.overrideVmargs
-showLocation
-Declipse.consoleLog=true
-debug
-vm /usr/lib/jvm/java-1.7.0-openjdk-1.7.0/jre/bin/../lib/i386/client/libjvm.so
-vmargs
-Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:PermSize=256M
-XX:MaxPermSize=512M
-Djava.class.path=/opt/voclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar 
Install location:
    file:/opt/voclipse/
Configuration file:
    file:/opt/voclipse/configuration/config.ini loaded
Configuration location:
    file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/
Configuration file:
    file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/config.ini loaded
Loading timestamp file from:
         file:/home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/   .baseConfigIniTimestamp
Timestamps found: 
         config.ini in the base: 1392658779000
         remembered 1391691411000
Shared configuration location:
    file:/opt/voclipse/configuration/
Framework located:
    file:/opt/voclipse/plugins/org.eclipse.osgi_3.10.0.v20140121-0337.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.0.v20140110-1728.jar
        eclipse.properties not found
Framework classpath:
    file:/opt/voclipse/plugins/org.eclipse.osgi_3.10.0.v20140121-0337.jar
    file:/opt/voclipse/plugins/
    file:/opt/voclipse/plugins/org.eclipse.osgi.compatibility.state_1.0.0.v20140110-1728.jar
Splash location:
    /home/matthias/.eclipse/1364444378_linux_gtk_x86/configuration/org.eclipse.equinox.launcher/com.vogella.vde_0.1.0.201402170042/splash.bmp
Debug options:
    file:/opt/voclipse/.options not found
```

Is the `file:/opt/voclipse/.options not found` suspicious or not an important file?

**Comment by Mailaender** [comment]
Ah, dang I fucked up this myself by starting it with sudo I guess. Will `rm -rf /opt/voclipse`

``` patch
--- /opt/voclipse/configuration/.settings/org.eclipse.ui.ide.prefs  2014-02-03 15:47:07.127098414 +0100
+++ /home/matthias/Downloads/opt/voclipse/configuration/.settings/org.eclipse.ui.ide.prefs  2014-02-17 18:54:07.009697794 +0100
@@ -1,5 +1,5 @@
 MAX_RECENT_WORKSPACES=5
-RECENT_WORKSPACES=/home/matthias/sudo-voclipse-workspace
+RECENT_WORKSPACES=/home/matthias/.voclipse/workplace
 RECENT_WORKSPACES_PROTOCOL=3
 SHOW_WORKSPACE_SELECTION_DIALOG=true
 eclipse.preferences.version=1
```
