### ISSUE TITLE
Retire Kepler release of voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#67]
The new dark theme uses functionality only available in Luna. We should retire the Kepler build.

**Comment by hendrikstill** [comment]
okay, should we stay at the two release build plan? 
Like stable/unstable and build a luna milestone build(stable) + cbi build(unstable) ?

**Comment by vogella** [comment]
I think we can do this after the Luna release. Kepler I think is not needed
at the moment.

2014-02-03 Hendrik S notifications@github.com:

**Comment by vogella** [comment]
I remove it from the website. @hendrikstill please retire the corresponding product plug-in. For the next release I would like to still have Luna and the next release following the existing naming conventions in which the plug-in name includes the release

**Comment by vogella** [comment]
Removed it from http://www.voclipse.com/

**Comment by hendrikstill** [comment]
Deactivated C-MASTER-com.vogella.vde job on the jenkins server.

> For the next release I would like to still have Luna and the next release following the existing naming conventions in which the plug-in name includes the release

I didn't get that.
