### ISSUE TITLE
Add (Vogella)Darktheme

### ISSUE THREAD

**Issue by hendrikstill** [vogellacompany/com.vogella.vde#7]
Because vogellacompany is the owner of this addon, there are two ways to build this:
1. Build the P2 Repository of the Theme and add this to the voclipse build
2. Integrate the Darktheme repository as git submodule to the voclipse build and integrate it into the maven build.

**Comment by vogella** [comment]
Don't put prio into this issue, I plan to migrate the Dark theme to
Eclipse. Org.
Am 04.12.2013 17:12 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
Okay, but this is maybe an interesting example how to integrade eclipse 3rd plugins into the build, This would be also an interesting topic for my thesis.

**Comment by vogella** [comment]
Is this example potentially similar to the e4 tools example?
Am 04.12.2013 19:25 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
But isn't the e4 tools an eclipse foundation hosted project? 
I would like have an example which shows how to add a eclipse extension from zero to build into voclipse. 
But I'll handle this topic with lower priority.

**Comment by vogella** [comment]
True.

2013/12/5 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
I cannot find the Job for the Vogella Darktheme on the jenkins server. Is it still available?

**Comment by vogella** [comment]
I don't remember doing anything with it.
Am 11.01.2014 10:27 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
8f22cdc adds the MoonRise UI Theme[1] instead of the "voclipse theme"  [2] .
Should we fork the MoonRise UI, as we did previously, or should we just reuse the MoonRise UI theme?

[1] https://github.com/guari/eclipse-ui-theme
[2] https://github.com/vogellacompany/eclipse-ui-theme

**Comment by hendrikstill** [comment]
Looks good on my mac 
![image](https://f.cloud.github.com/assets/374528/2020519/44c1add8-8833-11e3-90cb-ae25b9fd497e.png)

**Comment by vogella** [comment]
Reuse is good

2014-01-28 Hendrik S notifications@github.com

**Comment by hendrikstill** [comment]
As default?

**Comment by vogella** [comment]
+1
Am 28.01.2014 16:52 schrieb "Hendrik S" notifications@github.com:

**Comment by Mailaender** [comment]
> Looks good on my mac 

Indeed, slick.

**Comment by hendrikstill** [comment]
I guess we can close this issue
