### ISSUE TITLE
voclipse.exe fails on Windows 7

### ISSUE THREAD

**Issue by Mailaender** [vogellacompany/com.vogella.vde#77]
![image](https://f.cloud.github.com/assets/756669/2241230/d4bcc010-9cc6-11e3-8d08-c4b823d6faa9.png)

which pretty much breaks my https://github.com/Mailaender/com.voclipse.packaging shortcuts. It is probably a minor issue as the IDE starts when executing `eclipsec.exe` instead.

**Comment by hendrikstill** [comment]
Maybe a stupid question, but do you have a Java VM installed? 
I tested this 2 Weeks ago and it worked without any problem.

**Comment by Mailaender** [comment]
Yep, I installed a VM from http://java.com/download. I guess it won't startup via eclipsec.exe otherwise?

**Comment by Mailaender** [comment]
Or does this require a restart?

**Comment by hendrikstill** [comment]
Nop you are right. There is a problem with the voclipse.exe or its load mechanism.

**Comment by hendrikstill** [comment]
A was writing about the VM Settings which were set by the product configuration and thought that could be the reason for this problem. 
Can you remove the following lines from the <code>voclipse.ini</code>? 

<pre>
-vmargs
-Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:PermSize=256M
-XX:MaxPermSize=512M
</pre>

**Comment by Mailaender** [comment]
Renaming `voclipse.ini` to `voclipse.ini.bak` fixes it. The reason could be UNIX line endings.

![image](https://f.cloud.github.com/assets/756669/2268407/64de7e32-9ec9-11e3-9b89-20dd4c03b483.png)

Maybe use spaces to separate instead of newlines.

**Comment by Mailaender** [comment]
Oh wait, that is just Notepad.exe, Java/Eclipse is smarter. Removing

```
-vmargs
-Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:PermSize=256M
-XX:MaxPermSize=512M
```

fixes it.

**Comment by hendrikstill** [comment]
Okay, how much ram do you have in this machine?

**Comment by Mailaender** [comment]
![image](https://f.cloud.github.com/assets/756669/2268881/57f3bdfc-9ed0-11e3-9fa8-ccd2949c6fd7.png)

It is the same machine (dual-booting) where that parameter works on Linux with OpenJDK 7.

**Comment by Mailaender** [comment]
Shall I patch that at https://github.com/Mailaender/com.voclipse.packaging/blob/master/voclipse-setup.nsi or do we want to solve it here?

**Comment by vogella** [comment]
I think we should patch it directly in vde

2014-03-14 10:01 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by hendrikstill** [comment]
I guess df0bc55  should fix the problem.

**Comment by Mailaender** [comment]
Confirmed. This is fixed in Build id: 2014-03-14_12-55-54 after a rebuild https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/
