### ISSUE TITLE
Set the default activation key to all letters

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#80]
http://stackoverflow.com/questions/1959946/ctrl-space-in-eclipse-without-pressing-ctrl-space

**Comment by Mailaender** [comment]
Maybe try http://www.eclipse.org/recommenders/ instead of this hack?

**Comment by vogella** [comment]
Recommenders does not solve this
Am 20.03.2014 11:02 schrieb "Matthias Mailänder" notifications@github.com:

**Comment by Mailaender** [comment]
Also the delay for the auto-complete tooltip should be lowered by default imho.

**Comment by vogella** [comment]
In voclipse is should be already.
https://github.com/vogellacompany/com.vogella.vde/blob/master/com.vogella.vde/plugin_customization.ini#L62

2014-03-29 11:24 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by vogella** [comment]
I think this one is closed
