### ISSUE TITLE
Could not resolve module: org.eclipse.mylyn.java.ui 

### ISSUE THREAD

**Issue by Mailaender** [vogellacompany/com.vogella.vde#90]
```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.java.ui [569]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit
    -> Bundle-SymbolicName: org.eclipse.jdt.junit; bundle-version="3.7.300.v20131029-1808"; singleton:="true"
       org.eclipse.jdt.junit [222]
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.core; bundle-version="[3.6.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.core; bundle-version="3.7.300.v20131209-1856"; singleton:="true"
              org.eclipse.jdt.junit.core [223]
                Unresolved requirement: Require-Bundle: org.eclipse.equinox.simpleconfigurator.manipulator; bundle-version="[2.0.0,3.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.equinox.simpleconfigurator.manipulator; bundle-version="2.0.0.v20131217-1203"; singleton:="true"
                     org.eclipse.equinox.simpleconfigurator.manipulator [202]
                       Unresolved requirement: Import-Package: org.eclipse.equinox.internal.simpleconfigurator
```

**Comment by vogella** [comment]
Please stop writing bugs for what seems the same problem
Am 29.03.2014 11:43 schrieb "Matthias Mailänder" notifications@github.com:

**Comment by Mailaender** [comment]
Thought these were individual dependency problems.

**Comment by vogella** [comment]
Do you get it at startup or at the build?

**Comment by vogella** [comment]
If on the build, it seems like the Eclipse server were down for a bit, build seems to run again. https://build.vogella.com/ci/job/C-MASTER-com.vogella.vde.luna/190/console

**Comment by vogella** [comment]
If the build was the isuse, please verify that it works again and also all related issues

**Comment by Mailaender** [comment]
https://build.vogella.com/ci/job/C-MASTER-eclipse.platform.releng.aggregator/ is still broken (looks like https://build.vogella.com/ci/job/C-MASTER-eclipse.platform.releng.aggregator/146/org.eclipse.jdt$org.eclipse.jdt.annotation/ is the faulty one) and https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.vogella.vde.luna/ is from last week.

**Comment by Mailaender** [comment]
Btw: https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ will always grab the last successful one.

**Comment by Mailaender** [comment]
This seems to be gone in Build id: 2014-03-26_00-48-33.
